import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-products',
    standalone: true,
    imports: [CommonModule],
    templateUrl: './products.component.html',
    styleUrl: './products.component.scss',
})
export class ProductsComponent {
    products: any = [
        {
            name: 'PHIN SỮA ĐÁ',
            des: 'Hương vị cà phê Việt Nam đích thực! Từng hạt cà phê hảo hạng được chọn bằng tay, phối trộn độc đáo giữa hạt Robusta từ cao nguyên Việt Nam, thêm Arabica thơm lừng. Cà phê được pha từ Phin truyền thống, hoà cùng sữa đặc sánh và thêm vào chút đá tạo nên ly Phin Sữa Đá – Đậm Đà Chất Phin.',
            category_id: '1',
            sale: '4',
            view: 0,
            price: '60000',
            img: 'http://res.cloudinary.com/djcimgjcc/image/upload/v1697253504/ncjphfvwbpcvo8lohix7.jpg',
            createAt: '2023-10-14T03:18:24.173Z',
            id: 1,
        },
        {
            name: 'PHIN ĐEN ĐÁ',
            des: 'Dành cho những tín đồ cà phê đích thực! Hương vị cà phê truyền thống được phối trộn độc đáo tại Highlands. Cà phê đậm đà pha hoàn toàn từ Phin, cho thêm 1 thìa đường, một ít đá viên mát lạnh, tạo nên Phin Đen Đá mang vị cà phê đậm đà chất Phin.',
            category_id: '1',
            sale: '33',
            view: 0,
            price: '40000',
            img: 'http://res.cloudinary.com/djcimgjcc/image/upload/v1697253535/izfotfhf9bzgnshoepun.jpg',
            createAt: '2023-10-14T03:18:55.659Z',
            id: 2,
        },
        {
            name: 'BẠC XỈU ĐÁ',
            des: 'Nếu Phin Sữa Đá dành cho các bạn đam mê vị đậm đà, thì Bạc Xỉu Đá là một sự lựa chọn nhẹ “đô" cà phê nhưng vẫn thơm ngon, chất lừ không kém!',
            category_id: '1',
            sale: '5',
            view: 0,
            price: '50000',
            img: 'http://res.cloudinary.com/djcimgjcc/image/upload/v1697253572/ak1l4kxjxfkmergteg6w.jpg',
            createAt: '2023-10-14T03:19:33.216Z',
            id: 3,
        },
        {
            name: 'Trà thạch đào',
            des: 'Vị trà đậm đà kết hợp cùng những miếng đào thơm ngon mọng nước cùng thạch đào giòn dai. Thêm vào ít sữa để gia tăng vị béo.',
            category_id: '3',
            sale: '10',
            view: 0,
            price: '55000',
            img: 'http://res.cloudinary.com/djcimgjcc/image/upload/v1697253628/tvtea327qkmslscw8cvu.jpg',
            createAt: '2023-10-14T03:20:28.392Z',
            id: 4,
        },
        {
            name: 'TRÀ SEN VÀNG (SEN)',
            des: 'TRÀ SEN VÀNG (SEN)',
            category_id: '3',
            sale: '2',
            view: 0,
            price: '44000',
            img: 'http://res.cloudinary.com/djcimgjcc/image/upload/v1697253656/dl3tgwcgd10qosvgqhh5.jpg',
            createAt: '2023-10-14T03:20:56.871Z',
            id: 5,
        },
        {
            name: 'FREEZE SÔ-CÔ-LA',
            des: 'FREEZE SÔ-CÔ-LA',
            category_id: '5',
            sale: '10',
            view: 0,
            price: '88000',
            img: 'http://res.cloudinary.com/djcimgjcc/image/upload/v1697253735/y68b2sb5k0rcahdmsfne.jpg',
            createAt: '2023-10-14T03:22:15.361Z',
            id: 6,
        },
        {
            id: 7,
            name: 'COOKIES & CREAM',
            des: 'Một thức uống ngon lạ miệng bởi sự kết hợp hoàn hảo giữa cookies sô cô la giòn xốp cùng hỗn hợp sữa tươi cùng sữa đặc đem say với đá viên, và cuối cùng không thể thiếu được chính là lớp kem whip mềm mịn cùng cookies sô cô la say nhuyễn.',
            category_id: '5',
            sale: '22',
            view: 0,
            price: '70000',
            img: 'http://res.cloudinary.com/djcimgjcc/image/upload/v1697253773/w97dki0rjppggyauid0o.jpg',
            createAt: '2023-10-14T03:24:05.467Z',
        },
        {
            name: 'PHINDI KEM SỮA',
            des: 'Một thức uống ngon lạ miệng bởi sự kết hợp hoàn hảo giữa cookies sô cô la giòn xốp cùng hỗn hợp sữa tươi cùng sữa đặc đem say với đá viên, và cuối cùng không thể thiếu được chính là lớp kem whip mềm mịn cùng cookies sô cô la say nhuyễn.',
            category_id: '2',
            sale: '6',
            view: 0,
            price: '66000',
            img: 'http://res.cloudinary.com/djcimgjcc/image/upload/v1697253888/nj5t28xbzzowrjfk85wk.jpg',
            createAt: '2023-10-14T03:24:48.829Z',
            id: 8,
        },
        {
            name: 'TRÀ XANH ĐẬU ĐỎ',
            des: 'TRÀ XANH ĐẬU ĐỎ',
            category_id: '3',
            sale: '20',
            view: 0,
            price: '56000',
            img: 'http://res.cloudinary.com/djcimgjcc/image/upload/v1697253916/be5bcxcznfi7w6eorvtc.jpg',
            createAt: '2023-10-14T03:25:16.601Z',
            id: 9,
        },
    ];
}
